AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - Gemfile
Style/ClassAndModuleChildren:
  Enabled: false
Style/WhileUntilModifier:
  MaxLineLength: 110
Style/IfUnlessModifier:
  MaxLineLength: 110
Metrics/LineLength:
  Enabled: false
  Max;: 170
Metrics/ClassLength:
  Max: 170
Metrics/PerceivedComplexity:
  Max: 20
MethodLength:
  Max: 35
Metrics/ParameterLists:
  Max: 10
Metrics/AbcSize:
  Enabled: false
Style/PredicateName:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 10
Security/Eval:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - rake/**/*.rake
Style/VariableName:
  Enabled: false